<?
	require_once('definitions.inc');
	include('header.inc');
	LogIt($_SESSION['LogFile'], $_SESSION['UserID'], U_SIGNED_OUT, $_SESSION['UserRecID'], $_SESSION['LIPAddress'], $ErrMsg);    
	AuditIt($_SESSION['UserID'], 'خروج از سیستم', $_SESSION['LIPAddress'], (int)$_SESSION['SystemCode'], 0, $msg);
	session_unregister('SystemCode');
	echo HTMLStart('Sign Out');
	echo '<style type="text/css">INPUT, SELECT { font-family: Tahoma }';
	echo 'INPUT, SELECT { font-family: Tahoma (Arabic) }';
	echo '</style>';
	StartJavascript();
	echo 'var	ImgPic = \''.IMAGE_PATH.'SignOut\' + screen.width + \'.jpg\';';
	echo 'document.write(\'<body bgproperties="fixed" bgColor="#C8DEF0" link="#0000FF" alink="#0000FF" vlink="#0000FF" background="\' + ImgPic + \'">\');';
	EndJavascript();
	echo '<center>';
	echo Heading(2, 'سیستم مدیریت منابع و اطلاعات', '#CC9900');
	echo Heading(3, 'تهیه شده توسط مرکز کامپیوتر، آمار و اطلاعات دانشگاه فردوسی مشهد');
	echo StartTable();
	echo '<tr>';
	echo TableData('<b>مجری طرح:</b>', 'left');
	echo TableData('&nbsp;', 'left');
	echo '</tr><tr>';
	echo TableData('&nbsp;', 'left');
	echo TableData('<b><a href="http://www.um.ac.ir/~milanifard" target="_blank">امید میلانی فرد</a></b>', 'right');
	echo '</tr>';
	echo EndTable();	
	echo '<br>';
	echo StartTable();
	echo '<tr><td>';
	StartForm('', '../gateway/start.php', '');
	echo Input('ReEnter', 'ورود مجدد به سیستم', 'submit', 'style="background: #D6E7EF;border-bottom: 1px solid #104A7B;border-right: 1px solid #104A7B;border-left: 1px solid #AFC4D5;border-top:1px solid #AFC4D5;color:#000066;height:19px;text-decoration:none;cursor: hand"');
	EndForm();
	echo '</td><td>';
	StartForm('', '../shares/SOCompletely.php', '');
	echo Input('SignOutCompletely', 'خروج کامل', 'submit', 'style="background: #D6E7EF;border-bottom: 1px solid #104A7B;border-right: 1px solid #104A7B;border-left: 1px solid #AFC4D5;border-top:1px solid #AFC4D5;color:#000066;height:19px;text-decoration:none;cursor: hand"');
	EndForm();
	echo '</td></tr>';
	echo EndTable();
	echo '<font color="#FF0080"'.COPY_RIGHT_NOTE.'</font>';
	HTMLEnd();
?>